stages:
  download_data:
    cmd: >-
      wget https://git.io/vXTVC
      -O data/raw/dataset.csv
    outs:
    - data/raw/dataset.csv
  sampling:
    cmd: >-
      poetry run python -m chapter01.sampling
      data/raw/dataset.csv
      data/interim/trace.nc
      --samples=40000
      --sample_tune=10000
    deps:
    - chapter01/sampling.py
    - data/raw/dataset.csv
    outs:
    - data/interim/trace.nc
  analysis:
    cmd: >-
      poetry run python -m chapter01.analysis
      data/raw/dataset.csv
      data/interim/trace.nc
    deps:
    - data/raw/dataset.csv
    - data/interim/trace.nc
    outs:
    - reports/figures/chapter01/
