stages:
  download_data:
    cmd: >-
      wget https://git.io/vXTVC
      -O data/raw/dataset.csv
    outs:
    - data/raw/dataset.csv
  sampling:
    cmd: >-
      poetry run python -m chapter01.sampling
      data/raw/dataset.csv
      data/interim/trace.pickle
      data/interim/model.pickle
      --samples=40000
      --sample_tune=10000
    deps:
    - chapter01/sampling.py
    - data/raw/dataset.csv
    outs:
    - data/interim/trace.pickle
    - data/interim/model.pickle
  analysis:
    cmd: >-
      poetry run python -m chapter01.analysis
      data/raw/dataset.csv
      data/interim/trace.pickle
      data/interim/model.pickle
      reports/figures/chapter01/
      data/processed/trace_summary.csv
    deps:
    - chapter01/analysis.py
    - data/raw/dataset.csv
    - data/interim/trace.pickle
    - data/interim/model.pickle
    outs:
    - reports/figures/chapter01/
    - data/processed/trace_summary.csv
