stages:
  chap01_download_data:
    cmd: >-
      wget https://git.io/vXTVC
      -O data/raw/dataset.csv
    outs:
    - data/raw/dataset.csv
  chap01_sampling:
    cmd: >-
      poetry run python -m src.chapter01.sampling
      data/raw/dataset.csv
      data/interim/trace_and_model.pickle
      --samples=4000
      --sample_tune=1000
    deps:
    - src/chapter01/sampling.py
    - data/raw/dataset.csv
    outs:
    - data/interim/trace_and_model.pickle
  chap01_analysis:
    cmd: >-
      poetry run python -m src.chapter01.analysis
      data/raw/dataset.csv
      data/interim/trace_and_model.pickle
      reports/figures/chapter01/
      data/processed/trace_summary.csv
    deps:
    - src/chapter01/analysis.py
    - data/raw/dataset.csv
    - data/interim/trace_and_model.pickle
    outs:
    - reports/figures/chapter01/
    - data/processed/trace_summary.csv
  chap02_ab_testing:
    cmd: >-
      poetry run python -m src.chapter02.ab_testing
    deps:
    - src/chapter02/ab_testing.py
    outs:
    - reports/figures/chapter02/
