stages:
  chap01_download_data:
    cmd: >-
      wget https://git.io/vXTVC
      -O data/raw/dataset.csv
    outs:
    - data/raw/dataset.csv
  chap01_sampling:
    cmd: >-
      poetry run python -m src.chapter01.sampling
      data/raw/dataset.csv
      data/interim/trace_and_model.pickle
      --samples=4000
      --sample_tune=1000
    deps:
    - src/chapter01/sampling.py
    - src/utils.py
    - data/raw/dataset.csv
    outs:
    - data/interim/trace_and_model.pickle
  chap01_analysis:
    cmd: >-
      poetry run python -m src.chapter01.analysis
      data/raw/dataset.csv
      data/interim/trace_and_model.pickle
      reports/figures/chapter01/
      data/processed/trace_summary.csv
    deps:
    - src/chapter01/analysis.py
    - src/utils.py
    - data/raw/dataset.csv
    - data/interim/trace_and_model.pickle
    outs:
    - reports/figures/chapter01/
    - data/processed/trace_summary.csv
  chap02_one_bernoulli:
    cmd: >-
      poetry run python -m src.chapter02.one_bernoulli
      --figure_dir reports/figures/chapter02/one/
    deps:
    - src/chapter02/one_bernoulli.py
    - src/utils.py
    outs:
    - reports/figures/chapter02/one/bernoulli.png
  chap02_two_bernoulli_sampling:
    cmd: >-
      poetry run python -m src.chapter02.two_bernoulli_sampling
      --model_output_filepath models/chapter02/two_bernoulli.pickle
      --theta_filepath models/chapter02/two_bernoulli_theta.npz
    deps:
    - src/chapter02/two_bernoulli_sampling.py
    - src/utils.py
    outs:
    - models/chapter02/two_bernoulli.pickle
    - models/chapter02/two_bernoulli_theta.npz
  chap02_two_bernoulli_analysis:
    cmd: >-
      poetry run python -m src.chapter02.two_bernoulli_analysis
      models/chapter02/two_bernoulli.pickle
      models/chapter02/two_bernoulli_theta.npz
      data/processed/chapter02/two/
      --figure_dir reports/figures/chapter02/two/
    deps:
    - models/chapter02/two_bernoulli.pickle
    - models/chapter02/two_bernoulli_theta.npz
    - src/chapter02/two_bernoulli_analysis.py
    - src/utils.py
    outs:
    - reports/figures/chapter02/two/bernoulli.png
    - reports/figures/chapter02/two/trace.png
    - data/processed/chapter02/two/
